/* Dados locais: a sincronização Drive reutilizará este mesmo objeto. */
const STORAGE_KEY = "financas-pwa-data-v1";
const DEFAULT_GOOGLE_CLIENT_ID = "853627522281-41mlek5qtq27chktlkqjavuqi0944k7j.apps.googleusercontent.com";
const euro = new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" });
const state = { page: "transfers", month: currentMonth(), open: null, editingRule: null };
const buildVersion = () => window.APP_VERSION || "local";
document.title = `Finanças em ordem · ${buildVersion()}`;

function currentMonth() { return new Date().toISOString().slice(0, 7); }
function uid(prefix) { return `${prefix}-${crypto.randomUUID?.() || Date.now().toString(36)}`; }
function seed() {
  return { schemaVersion: 1, updatedAt: new Date().toISOString(), registos: [], dividas: [], transfers: {
    people: [
      { id: "pessoa-a", name: "Pessoa A", transferDays: [2], planningMonthOffset: 0 },
      { id: "pessoa-b", name: "Pessoa B", transferDays: [25], planningMonthOffset: 1 }
    ],
    accounts: [
      { id: "conta-a", name: "Conta principal A", ownerId: "pessoa-a" },
      { id: "conta-b", name: "Conta principal B", ownerId: "pessoa-b" }
    ],
    destinations: [
      { id: "conta-comum", name: "Conta comum" },
      { id: "poupanca", name: "Poupança" }
    ],
    monthlyIncomes: { "pessoa-a": 200000, "pessoa-b": 180000 },
    monthlyRules: [
      ["Contribuição comum", "pessoa-a", "conta-a", "conta-comum", 50000, "despesa"],
      ["Poupança", "pessoa-a", "conta-a", "poupanca", 15000, "poupanca"],
      ["Contribuição comum", "pessoa-b", "conta-b", "conta-comum", 50000, "despesa"]
    ].map(([name, personId, sourceAccountId, destinationId, amountCents, kind]) => ({ id:uid("rule"), name, personId, sourceAccountId, destinationId, amountCents, kind, group:true, active:true })),
    monthlyExecutions: {}, drive: { clientId: "", fileId: "", syncStatus: "local" }
  }};
}
let data;
try { data = JSON.parse(localStorage.getItem(STORAGE_KEY)) || seed(); } catch { data = seed(); }
function save() { data.updatedAt = new Date().toISOString(); localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); render(); }
const tr = () => data.transfers;
const googleClientId = () => tr().drive.clientId || DEFAULT_GOOGLE_CLIENT_ID;
function incomes() { return tr().monthlyIncomes ||= Object.fromEntries(tr().people.map((person) => [person.id, 0])); }
const getById = (items, id) => items.find((x) => x.id === id);
const money = (cents) => euro.format((cents || 0) / 100);
const monthLabel = (month) => new Intl.DateTimeFormat("pt-PT", { month:"long", year:"numeric" }).format(new Date(`${month}-02T12:00:00`));
function shiftMonth(month, n) { const d = new Date(`${month}-01T12:00:00`); d.setMonth(d.getMonth() + n); return d.toISOString().slice(0,7); }
function personFor(id) { return getById(tr().people,id); }
function accountFor(id) { return getById(tr().accounts,id); }
function destFor(id) { return getById(tr().destinations,id); }
function groupId(rule) { return rule.group ? `${rule.personId}|${rule.sourceAccountId}|${rule.destinationId}` : rule.id; }
function monthlyGroups(month) {
  const groups = new Map();
  tr().monthlyRules.filter((r) => r.active).forEach((rule) => {
    const key = groupId(rule); if (!groups.has(key)) groups.set(key, { id:key, ruleIds:[], rules:[], personId:rule.personId, sourceAccountId:rule.sourceAccountId, destinationId:rule.destinationId });
    const g = groups.get(key); g.rules.push(rule); g.ruleIds.push(rule.id);
  });
  return [...groups.values()].map((g) => ({ ...g, plannedAmountCents:g.rules.reduce((a,r) => a+r.amountCents,0), execution: tr().monthlyExecutions[month]?.find((e) => e.id === `${month}-${g.id}`) }));
}
function execFor(group) { return group.execution || { status:"pending", plannedAmountCents:group.plannedAmountCents }; }
function scheduledText(group, month) { const p = personFor(group.personId); const executionMonth = shiftMonth(month, -p.planningMonthOffset); return `${p.transferDays.map((d)=>`${d}`).join(" ou ")} ${new Intl.DateTimeFormat("pt-PT",{month:"short"}).format(new Date(`${executionMonth}-02T12:00:00`))}`; }
function render() { document.querySelector("#app").innerHTML = state.page === "transfers" ? transferPage() : state.page === "rules" ? rulesPage() : state.page === "patrimony" ? window.patrimonyPage() : settingsPage(); bind(); }
function transferPage() {
  const groups = monthlyGroups(state.month), pending = groups.filter((g)=>execFor(g).status === "pending"), done = groups.filter((g)=>execFor(g).status !== "pending");
  const total = pending.reduce((a,g)=>a+g.plannedAmountCents,0);
  const plannedTotal = groups.filter((g)=>execFor(g).status !== "skipped").reduce((a,g)=>a+(execFor(g).actualAmountCents ?? g.plannedAmountCents),0);
  const totalIncome = tr().people.reduce((sum,p)=>sum+(incomes()[p.id]||0),0);
  const each = tr().people.map((p)=>{const planned=groups.filter(g=>g.personId===p.id&&execFor(g).status!=="skipped").reduce((a,g)=>a+(execFor(g).actualAmountCents ?? g.plannedAmountCents),0);return {p, amount:pending.filter(g=>g.personId===p.id).reduce((a,g)=>a+g.plannedAmountCents,0), remaining:(incomes()[p.id]||0)-planned};});
  return `<header class="top"><div><p class="eyebrow">Planeamento mensal</p><h1>Transferências</h1></div><div class="top-actions"><span class="build-version" title="Versão publicada">${buildVersion()}</span><button class="icon-button" data-action="sync" aria-label="Sincronizar">↻</button></div></header>
  <div class="month-picker"><button class="icon-button" data-month="-1">‹</button><strong>${monthLabel(state.month)}</strong><button class="icon-button" data-month="1">›</button></div>
  <section class="summary"><div class="summary-heading"><div><small>Por transferir</small><div class="summary-value">${money(total)}</div><small>${pending.length} movimento${pending.length===1?"":"s"} pendente${pending.length===1?"":"s"}</small></div><button class="summary-edit" data-action="edit-income">Rendimentos</button></div><div class="summary-grid"><div><small>Disponível após transferências</small><div class="summary-value">${money(totalIncome-plannedTotal)}</div><small>Rendimento mensal: ${money(totalIncome)}</small></div><div class="person-totals">${each.map(({p,remaining})=>`<div class="person-total"><span>${p.name}</span><strong>${money(remaining)}</strong></div>`).join("")}</div></div></section>
  <div class="section-title"><h2>Por fazer</h2><span class="muted">${pending.length}</span></div>${pending.length ? pending.map((g)=>card(g)).join("") : `<div class="empty-card">Tudo tratado neste mês.</div>`}
  ${done.length ? `<div class="section-title"><h2>Concluídas</h2><span class="muted">${done.length}</span></div>${done.map((g)=>card(g)).join("")}` : ""}${nav()}`;
}
function card(g) { const ex = execFor(g), p=personFor(g.personId), account=accountFor(g.sourceAccountId), dest=destFor(g.destinationId), isOpen=state.open===g.id; const label={pending:"Pendente",done:"Efetuada",skipped:"Dispensada"}[ex.status]; return `<article class="transfer-card ${ex.status==="done"?"is-done":""}"><button class="transfer-main" data-open="${g.id}"><div class="route">${p.name} <span>· ${account.name} → ${dest.name}</span></div><div class="amount">${money(ex.actualAmountCents ?? g.plannedAmountCents)}</div><div class="card-note">${g.rules.map(r=>r.name).join(" · ")} · dia ${scheduledText(g,state.month)}</div><span class="status ${ex.status}">${label}</span></button>${isOpen?`<div class="details"><ul class="breakdown">${g.rules.map(r=>`<li><span>${r.name}</span><strong>${money(r.amountCents)}</strong></li>`).join("")}</ul><div class="actions">${ex.status==="pending"?`<button class="button" data-complete="${g.id}">Marcar efetuada</button><button class="button secondary" data-skip="${g.id}">Dispensar</button>`:`<button class="button secondary" data-reset="${g.id}">Reabrir</button>`}</div></div>`:""}</article>`; }
function nav() { return `<nav class="bottom-nav"><button class="nav-button ${state.page==="transfers"?"active":""}" data-page="transfers">Transferências</button><button class="nav-button ${state.page==="patrimony"?"active":""}" data-page="patrimony">Património</button><button class="nav-button ${state.page==="rules"?"active":""}" data-page="rules">Rubricas</button><button class="nav-button ${state.page==="settings"?"active":""}" data-page="settings">Dados</button></nav>`; }
function rulesPage() { return `<header class="page-header"><div><p class="eyebrow">Configuração</p><h1>Rubricas</h1></div><button class="button" data-action="new-rule">+ Nova</button></header><p class="help">As rubricas com a mesma pessoa, origem e destino são agrupadas numa única transferência.</p>${tr().monthlyRules.filter(r=>r.active).map(r=>{const p=personFor(r.personId),a=accountFor(r.sourceAccountId),d=destFor(r.destinationId);return `<div class="list-row"><div><strong>${r.name} · ${money(r.amountCents)}</strong><span>${p.name} · ${a.name} → ${d.name}</span></div><div class="row-actions"><button class="small-button" data-edit="${r.id}">Editar</button><button class="small-button" data-disable="${r.id}">Pausar</button></div></div>`}).join("") || `<div class="empty-card">Ainda não existem rubricas.</div>`}${nav()}`; }
function settingsPage() { const drive=tr().drive; return `<header class="page-header"><div><p class="eyebrow">Dados e sincronização</p><h1>Google Drive</h1></div></header><p class="help">Os dados ficam primeiro neste dispositivo. A primeira sincronização cria <strong>financas-pwa.json</strong>. Noutro telemóvel, escolha <strong>Ligar ao Drive</strong>, autorize a conta Google e a app encontra automaticamente o ficheiro.</p><div class="list-row"><div><strong>Estado</strong><span>${drive.fileId?"Ficheiro Drive associado":"Apenas neste dispositivo"}</span></div><button class="small-button" data-action="drive-settings">OAuth</button></div><div class="list-row"><div><strong>Ligar ao Drive</strong><span>${drive.fileId?"Procura novamente e carrega a cópia remota":"Encontra e carrega financas-pwa.json"}</span></div><button class="small-button" data-action="drive-connect">Ligar</button></div>${drive.fileId?`<div class="list-row"><div><strong>Carregar do Drive</strong><span>Substitui a cópia local pela versão remota</span></div><button class="small-button" data-action="drive-load">Carregar</button></div>`:""}<div class="list-row"><div><strong>Exportar cópia</strong><span>Guarda o JSON completo neste dispositivo</span></div><button class="small-button" data-action="export">Exportar</button></div><div class="list-row"><div><strong>Importar cópia</strong><span>Substitui os dados locais por um ficheiro JSON</span></div><button class="small-button" data-action="import">Importar</button></div><input id="import-file" type="file" accept="application/json" hidden>${nav()}`; }
function openIncomeEditor(){const dlg=document.createElement("dialog");dlg.innerHTML=`<form class="modal" method="dialog" id="income-form"><div class="modal-head"><h2>Rendimentos mensais</h2><button class="icon-button" value="cancel">×</button></div><p class="help">Valores usados para calcular o dinheiro disponível depois de todas as transferências planeadas.</p><div class="form-grid">${tr().people.map(p=>`<label class="full">${p.name}<input required min="0" step="0.01" type="number" name="${p.id}" value="${((incomes()[p.id]||0)/100).toFixed(2)}"></label>`).join("")}</div><div class="modal-actions"><button class="button secondary" value="cancel">Cancelar</button><button class="button" value="default">Guardar</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener("close",()=>dlg.remove());dlg.querySelector("#income-form").addEventListener("submit",()=>{const f=new FormData(dlg.querySelector("#income-form"));tr().people.forEach(p=>{incomes()[p.id]=Math.round(Number(f.get(p.id))*100);});save();toast("Rendimentos guardados");});}
function openRule(rule) { state.editingRule=rule || null; const r=rule || { name:"",personId:tr().people[0].id,sourceAccountId:tr().accounts[0].id,destinationId:tr().destinations[0].id,amountCents:0,kind:"despesa",group:true,active:true }; const opts=(items,sel)=>items.map(x=>`<option value="${x.id}" ${x.id===sel?"selected":""}>${x.name}</option>`).join(""); const dlg=document.createElement("dialog"); dlg.innerHTML=`<form class="modal" method="dialog" id="rule-form"><div class="modal-head"><h2>${rule?"Editar rubrica":"Nova rubrica"}</h2><button class="icon-button" value="cancel">×</button></div><div class="form-grid"><label class="full">Nome<input required name="name" value="${r.name}"></label><label>Valor (€)<input required min="0" step="0.01" type="number" name="amount" value="${(r.amountCents/100).toFixed(2)}"></label><label>Tipo<select name="kind"><option value="despesa">Despesa corrente</option><option value="poupanca">Poupança</option><option value="despesa_futura">Objetivo futuro</option><option value="transferencia_fixa">Transferência fixa</option></select></label><label>Pessoa<select name="personId">${opts(tr().people,r.personId)}</select></label><label>Conta de origem<select name="sourceAccountId">${opts(tr().accounts,r.sourceAccountId)}</select></label><label class="full">Destino<select name="destinationId">${opts(tr().destinations,r.destinationId)}</select></label><label class="toggle full"><input type="checkbox" name="group" ${r.group?"checked":""}>Agrupar quando origem e destino coincidirem</label></div><div class="modal-actions"><button class="button secondary" value="cancel">Cancelar</button><button class="button" value="default">Guardar</button></div></form>`; document.body.append(dlg); dlg.showModal(); dlg.querySelector("select[name=kind]").value=r.kind; dlg.addEventListener("close",()=>dlg.remove()); dlg.querySelector("#rule-form").addEventListener("submit",()=>{const f=new FormData(dlg.querySelector("#rule-form")); const item={...r,id:r.id||uid("rule"),name:f.get("name").trim(),personId:f.get("personId"),sourceAccountId:f.get("sourceAccountId"),destinationId:f.get("destinationId"),amountCents:Math.round(Number(f.get("amount"))*100),kind:f.get("kind"),group:f.has("group"),active:true}; const i=tr().monthlyRules.findIndex(x=>x.id===item.id); if(i>-1)tr().monthlyRules[i]=item; else tr().monthlyRules.push(item); save(); toast("Rubrica guardada");}); }
function setExecution(group,status) { const list=tr().monthlyExecutions[state.month] ||= []; const id=`${state.month}-${group.id}`, index=list.findIndex(e=>e.id===id); if(status==="pending") { if(index>-1) list.splice(index,1); } else { const record={id,ruleIds:group.ruleIds,plannedAmountCents:group.plannedAmountCents,status,completedAt:new Date().toISOString().slice(0,10),actualAmountCents:group.plannedAmountCents,note:""}; if(index>-1)list[index]=record; else list.push(record); } state.open=null; save(); toast(status==="done"?"Transferência registada":"Transferência atualizada"); }
function bind() { document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.open=null;render();}); document.querySelectorAll("[data-month]").forEach(b=>b.onclick=()=>{state.month=shiftMonth(state.month,Number(b.dataset.month));state.open=null;render();}); document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{state.open=state.open===b.dataset.open?null:b.dataset.open;render();}); const group=(id)=>monthlyGroups(state.month).find(g=>g.id===id); document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>setExecution(group(b.dataset.complete),"done")); document.querySelectorAll("[data-skip]").forEach(b=>b.onclick=()=>setExecution(group(b.dataset.skip),"skipped")); document.querySelectorAll("[data-reset]").forEach(b=>b.onclick=()=>setExecution(group(b.dataset.reset),"pending")); document.querySelector("[data-action=new-rule]")?.addEventListener("click",()=>openRule()); document.querySelector("[data-action=edit-income]")?.addEventListener("click",openIncomeEditor); document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openRule(getById(tr().monthlyRules,b.dataset.edit))); document.querySelectorAll("[data-disable]").forEach(b=>b.onclick=()=>{getById(tr().monthlyRules,b.dataset.disable).active=false;save();toast("Rubrica pausada");}); document.querySelector("[data-action=export]")?.addEventListener("click",exportData); document.querySelector("[data-action=import]")?.addEventListener("click",()=>document.querySelector("#import-file").click()); document.querySelector("#import-file")?.addEventListener("change",importData); document.querySelector("[data-action=sync]")?.addEventListener("click",syncDrive); document.querySelector("[data-action=drive-settings]")?.addEventListener("click",driveSettings); document.querySelector("[data-action=drive-connect]")?.addEventListener("click",connectDrive); document.querySelector("[data-action=drive-load]")?.addEventListener("click",loadDrive); if(state.page==="patrimony")window.bindPatrimony(); }
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="financas-pwa.json";a.click();URL.revokeObjectURL(a.href);}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const candidate=JSON.parse(reader.result);if(!candidate.transfers)throw Error();data=candidate;save();toast("Dados importados");}catch{toast("Este ficheiro não contém dados válidos.");}};reader.readAsText(file);}
function driveSettings(){const id=prompt("ID de cliente OAuth Google (Web application):",googleClientId());if(id===null)return;tr().drive.clientId=id.trim()===DEFAULT_GOOGLE_CLIENT_ID?"":id.trim();save();toast("Configuração Google guardada");}
function googleScript() { return new Promise((resolve,reject)=>{ if(window.google?.accounts?.oauth2) return resolve(); const s=document.createElement("script"); s.src="https://accounts.google.com/gsi/client";s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error("Não foi possível carregar a autenticação Google."));document.head.append(s); }); }
async function googleToken(){ await googleScript(); return new Promise((resolve,reject)=>{ const client=google.accounts.oauth2.initTokenClient({client_id:googleClientId(),scope:"https://www.googleapis.com/auth/drive.file",callback:(response)=>response.error?reject(new Error(response.error)):resolve(response.access_token)});client.requestAccessToken({prompt:"consent"}); }); }
window.googleTokenForPortfolio = googleToken;
async function findDriveFile(token){const query=encodeURIComponent("name = 'financas-pwa.json' and trashed = false");const response=await fetch(`https://www.googleapis.com/drive/v3/files?q=${query}&spaces=drive&orderBy=modifiedTime desc&pageSize=1&fields=files(id,name,modifiedTime)`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Não foi possível procurar o ficheiro no Drive.");const result=await response.json();return result.files?.[0]||null;}
async function connectDrive(){try{toast("A procurar a cópia no Google Drive…");const token=await googleToken();const file=await findDriveFile(token);if(!file){toast("Não encontrei financas-pwa.json. Sincronize neste dispositivo para o criar.");return;}tr().drive.fileId=file.id;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));await loadDrive(token);}catch(error){toast(error.message||"Não foi possível ligar ao Drive.");}}
async function syncDrive(){ try { toast("A ligar ao Google Drive…");const token=await googleToken();if(!tr().drive.fileId){const existing=await findDriveFile(token);if(existing){tr().drive.fileId=existing.id;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render();toast("Já existe uma cópia no Drive. Use Ligar ao Drive para a carregar primeiro.");return;}}const json=JSON.stringify(data,null,2);let response;if(tr().drive.fileId){response=await fetch(`https://www.googleapis.com/upload/drive/v3/files/${tr().drive.fileId}?uploadType=media`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:json});}else{const boundary=`financas${Date.now()}`;const body=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name:"financas-pwa.json",mimeType:"application/json"})}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${json}\r\n--${boundary}--`],{type:`multipart/related; boundary=${boundary}`});response=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart",{method:"POST",headers:{Authorization:`Bearer ${token}`},body});}if(!response.ok)throw new Error("O Google Drive recusou a gravação.");const result=await response.json();if(result.id){tr().drive.fileId=result.id;await fetch(`https://www.googleapis.com/upload/drive/v3/files/${result.id}?uploadType=media`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(data,null,2)});}tr().drive.syncStatus="synced";localStorage.setItem(STORAGE_KEY,JSON.stringify(data));render();toast("Dados sincronizados com o Drive.");}catch(error){tr().drive.syncStatus="error";localStorage.setItem(STORAGE_KEY,JSON.stringify(data));toast(error.message||"Não foi possível sincronizar.");} }
async function loadDrive(token){try{const clientId=googleClientId(),fileId=tr().drive.fileId;toast("A carregar do Google Drive…");token ||= await googleToken();const response=await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Não foi possível ler o ficheiro no Drive.");const remote=await response.json();if(!remote.transfers)throw new Error("O ficheiro Drive não é uma base de dados desta PWA.");data=remote;data.transfers.drive={...(data.transfers.drive||{}),clientId,fileId,syncStatus:"synced"};save();toast("Versão do Drive carregada.");}catch(error){toast(error.message||"Não foi possível carregar.");}}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600);}
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js");
render();
