(() => {
  const KEY = "patrimonio-pwa-data-v1", FILE = "patrimonio-pwa.json";
  const euro = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR" });
  let selectedMonth = "";
  let loadedFromDrive = false;
  let portfolio;
  try { portfolio = JSON.parse(localStorage.getItem(KEY)); } catch { portfolio = null; }
  const empty = () => ({ schemaVersion:1, updatedAt:new Date().toISOString(), registos:[], dividas:[], catalog:{products:[],notesByProduct:{}}, drive:{fileName:FILE,fileId:"",syncStatus:"local"} });
  const p = () => portfolio || empty();
  const month = (date) => date.slice(0,7);
  const key = (institution, product) => `${institution}|${product}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
  const save = () => { p().updatedAt=new Date().toISOString(); localStorage.setItem(KEY,JSON.stringify(p())); };
  const months = () => [...new Set(p().registos.map(r=>month(r.data)).concat(p().dividas.map(d=>month(d.data))))].sort().reverse();
  const current = () => selectedMonth || months()[0] || new Date().toISOString().slice(0,7);
  const label = (m) => new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(new Date(`${m}-02T12:00:00`));
  function variation(record){const prior=p().registos.filter(r=>r.instituicao===record.instituicao&&r.produto===record.produto&&r.data<record.data).sort((a,b)=>b.data.localeCompare(a.data))[0];if(!prior||!Number(prior.valor))return "Sem histórico anterior";const delta=Number(record.valor)-Number(prior.valor),sign=delta>0?"+":delta<0?"−":"",percent=(delta/Number(prior.valor))*100;return `<span class="variation ${delta<0?"negative":delta>0?"positive":""}">${sign}${euro.format(Math.abs(delta))} · ${sign}${Math.abs(percent).toFixed(1)}%</span>`;}
  const nav = () => `<nav class="bottom-nav"><button class="nav-button" data-page="transfers">Transferências</button><button class="nav-button" data-page="rules">Rubricas</button><button class="nav-button active patrimony-nav" data-page="patrimony">Património</button><button class="nav-button" data-page="settings">Dados</button></nav>`;
  function page(){
    if(!portfolio) return `<header class="page-header patrimony-head"><div><p class="eyebrow">Património</p><h1>Começar histórico</h1></div></header><div class="empty-card"><p>Importe o seu ficheiro histórico <strong>bens.json</strong> ou <strong>patrimonio-pwa.json</strong>. Os dados ficam locais até os sincronizar com o Drive.</p><br><button class="button patrimony-button" data-p-import>Importar histórico</button><input id="patrimony-import" type="file" accept="application/json" hidden></div>${nav()}`;
    const m=current(), rows=p().registos.filter(r=>month(r.data)===m), debts=p().dividas.filter(d=>month(d.data)===m), assets=rows.reduce((sum,r)=>sum+Number(r.valor||0),0), debt=debts.reduce((sum,d)=>sum+Number(d.valor||0),0), loadWarning=loadedFromDrive?"":`<p class="help patrimony-warning">Esta cópia ainda não foi carregada do Drive nesta sessão. Use <strong>Dados → Ligar</strong> antes de alterar ou sincronizar.</p>`;
    return `<header class="page-header patrimony-head"><div><p class="eyebrow">Património</p><h1>${label(m)}</h1></div><div class="top-actions"><button class="button patrimony-button" data-p-new>+ Registo</button><button class="icon-button patrimony-sync" data-p-sync aria-label="Sincronizar património">↻</button></div></header>${loadWarning}<div class="month-picker patrimony-picker"><button class="icon-button" data-p-month="-1">‹</button><strong>${label(m)}</strong><button class="icon-button" data-p-month="1">›</button></div><section class="summary patrimony-summary"><div class="summary-heading"><div><small>Património líquido</small><div class="summary-value">${euro.format(assets-debt)}</div><small>Ativos menos dívidas</small></div><button class="summary-edit" data-p-note>+ Nota</button></div><div class="summary-grid"><div><small>Ativos</small><div class="summary-value">${euro.format(assets)}</div></div><div><small>Dívidas</small><div class="summary-value">${euro.format(debt)}</div></div></div></section><div class="section-title"><h2>Ativos</h2><span class="muted">${rows.length}</span></div>${rows.length?rows.map(r=>`<div class="list-row patrimony-row"><div><strong>${r.instituicao} · ${r.produto}</strong><span>${r.data} · ${variation(r)}</span></div><strong>${euro.format(r.valor)}</strong></div>`).join(""):`<div class="empty-card">Sem registos neste mês.</div>`}<div class="section-title"><h2>Dívidas</h2><button class="small-button patrimony-debt" data-p-debt>+ Dívida</button></div>${debts.length?debts.map(d=>`<div class="list-row patrimony-row"><div><strong>${d.tipo||"Dívida"}</strong><span>${d.data}</span></div><strong>${euro.format(d.valor)}</strong></div>`).join(""):`<div class="empty-card">Sem dívidas neste mês.</div>`}${nav()}`;
  }
  function chooseMonth(offset){const all=months().sort();const i=all.indexOf(current());selectedMonth=all[Math.max(0,Math.min(all.length-1,i+offset))]||current();render();}
  function render(){ document.querySelector("#app").innerHTML=page(); window.bind(); }
  function normalize(input){const raw=input.registos?input:empty();const out={...empty(),...raw,catalog:{products:raw.catalog?.products||[],notesByProduct:raw.catalog?.notesByProduct||{}},drive:{...empty().drive,...raw.drive,fileName:FILE}};for(const r of out.registos){if(!out.catalog.products.some(x=>x.id===key(r.instituicao,r.produto)))out.catalog.products.push({id:key(r.instituicao,r.produto),institution:r.instituicao,product:r.produto});}return out;}
  function importFile(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{portfolio=normalize(JSON.parse(reader.result));save();selectedMonth="";render();toast("Histórico importado neste dispositivo.");}catch{toast("O ficheiro não contém um histórico válido.");}};reader.readAsText(file);}
  function newRecord(){const selected=current(),date=`${selected}-${String(new Date(Number(selected.slice(0,4)),Number(selected.slice(5,7)),0).getDate()).padStart(2,"0")}`, institutions=[...new Set(p().catalog.products.map(x=>x.institution))].sort().map(x=>`<option value="${x}"></option>`).join(""),products=[...new Set(p().catalog.products.map(x=>x.product))].sort().map(x=>`<option value="${x}"></option>`).join(""),missing=p().catalog.products.filter(x=>!p().registos.some(r=>month(r.data)===selected&&r.instituicao===x.institution&&r.produto===x.product)),missingHelp=missing.length?`<p class="help patrimony-missing"><strong>Ainda sem registo em ${label(selected)}:</strong><br>${missing.map(x=>`${x.institution} · ${x.product}`).join("<br>")}</p>`:"";const dlg=document.createElement("dialog");dlg.innerHTML=`<form class="modal" method="dialog" id="p-form" autocomplete="off"><div class="modal-head"><h2>Novo registo</h2><button class="icon-button patrimony-close" value="cancel" formnovalidate>×</button></div>${missingHelp}<div class="form-grid"><label>Instituição<input required name="institution" list="p-institutions" autocomplete="off"></label><label>Produto<input required name="product" list="p-products" autocomplete="off"></label><label>Valor (€)<input required min="0" step="0.01" type="number" name="value"></label><label>Data<input required type="date" name="date" value="${date}"></label><label class="full">Observação<input name="note" maxlength="240" autocomplete="off"></label></div><datalist id="p-institutions">${institutions}</datalist><datalist id="p-products">${products}</datalist><div class="modal-actions"><button class="button secondary" value="cancel" formnovalidate>Cancelar</button><button class="button patrimony-button" value="default">Guardar</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener("close",()=>dlg.remove());dlg.querySelector("#p-form").addEventListener("submit",(event)=>{if(event.submitter?.value==="cancel")return;const f=new FormData(dlg.querySelector("#p-form")),institution=f.get("institution").trim(),product=f.get("product").trim(),date=f.get("date"),id=key(institution,product),record={data:date,instituicao:institution,produto:product,valor:Number(f.get("value"))},index=p().registos.findIndex(r=>month(r.data)===month(date)&&r.instituicao===institution&&r.produto===product);if(index>-1&&!confirm(`Já existe um registo de ${institution} · ${product} neste mês. Pretende substituí-lo?`)){event.preventDefault();return;}if(index>-1)p().registos[index]=record;else p().registos.push(record);if(!p().catalog.products.some(x=>x.id===id))p().catalog.products.push({id,institution,product});if(f.get("note").trim())(p().catalog.notesByProduct[id]||={})[month(date)]=f.get("note").trim();save();selectedMonth=month(date);render();toast(index>-1?"Registo substituído.":"Registo guardado.");});}
  function monthEnd(){const m=current();return `${m}-${String(new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate()).padStart(2,"0")}`;}
  function dialog(title,fields,onSave){const dlg=document.createElement("dialog");dlg.innerHTML=`<form class="modal" method="dialog" id="portfolio-form"><div class="modal-head"><h2>${title}</h2><button class="icon-button patrimony-close" value="cancel" formnovalidate>×</button></div><div class="form-grid">${fields}</div><div class="modal-actions"><button class="button secondary" value="cancel" formnovalidate>Cancelar</button><button class="button patrimony-button" value="default">Guardar</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener("close",()=>dlg.remove());dlg.querySelector("#portfolio-form").addEventListener("submit",e=>{if(e.submitter?.value!=="cancel")onSave(new FormData(e.currentTarget));});}
  function newDebt(){dialog("Nova dívida",`<label>Tipo<select name="type"><option value="casa">Casa</option><option value="carro">Carro</option><option value="outra">Outra</option></select></label><label>Valor em dívida (€)<input required min="0" step="0.01" type="number" name="value"></label><label class="full">Data<input required type="date" name="date" value="${monthEnd()}"></label>`,f=>{const date=f.get("date"),type=f.get("type"),record={data:date,tipo:type,valor:Number(f.get("value"))},index=p().dividas.findIndex(d=>month(d.data)===month(date)&&(d.tipo||"divida")===type);if(index>-1&&!confirm(`Já existe uma dívida de ${type} neste mês. Pretende substituí-la?`))return;if(index>-1)p().dividas[index]=record;else p().dividas.push(record);save();selectedMonth=month(date);render();toast(index>-1?"Dívida substituída.":"Dívida guardada.");});}
  function newNote(){const options=p().catalog.products.map(x=>`<option value="${x.id}">${x.institution} · ${x.product}</option>`).join("");dialog("Nova nota",`<label class="full">Produto<select required name="product">${options}</select></label><label>Data<input required type="date" name="date" value="${monthEnd()}"></label><label class="full">Observação<textarea required name="note" maxlength="240"></textarea></label>`,f=>{(p().catalog.notesByProduct[f.get("product")]||={})[month(f.get("date"))]=f.get("note").trim();save();render();toast("Nota guardada.");});}
  async function token(){return window.googleTokenForPortfolio();}
  async function find(access){const q=encodeURIComponent(`name = '${FILE}' and trashed = false`),r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&orderBy=modifiedTime desc&pageSize=1&fields=files(id)`,{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw Error("Não foi possível procurar o ficheiro no Drive.");return (await r.json()).files?.[0];}
  async function connect(access){try{access ||= await token();const file=await find(access);if(!file){toast("Ainda não existe patrimonio-pwa.json no Drive. Sincronize o património para o criar.");return;}const r=await fetch(`https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`,{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw Error("Não foi possível carregar o património.");portfolio=normalize(await r.json());p().drive.fileId=file.id;loadedFromDrive=true;save();selectedMonth="";render();toast("Património carregado do Drive.");}catch(e){toast(e.message||"Não foi possível ligar ao Drive.");}}
  async function sync(){if(!portfolio){toast("Importe primeiro o histórico.");return;}try{const access=await token();let id=p().drive.fileId;if(!id){const found=await find(access);if(found){toast("Já existe uma cópia no Drive. Use Ligar para a carregar.");return;}const created=await fetch("https://www.googleapis.com/drive/v3/files",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({name:FILE,mimeType:"application/json"})});if(!created.ok)throw Error("O Drive recusou a criação do ficheiro.");id=(await created.json()).id;p().drive.fileId=id;}const body=JSON.stringify(p(),null,2),headers={Authorization:`Bearer ${access}`,"Content-Type":"application/json"};const r=await fetch(`https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media`,{method:"PATCH",headers,body});if(!r.ok)throw Error("O Drive recusou a gravação.");save();render();toast("Património sincronizado.");}catch(e){toast(e.message||"Não foi possível sincronizar.");}}
  window.patrimonyPage=page;window.connectPatrimony=connect;window.bindPatrimony=()=>{document.querySelector("[data-p-import]")?.addEventListener("click",()=>document.querySelector("#patrimony-import").click());document.querySelector("#patrimony-import")?.addEventListener("change",importFile);document.querySelector("[data-p-new]")?.addEventListener("click",newRecord);document.querySelector("[data-p-note]")?.addEventListener("click",newNote);document.querySelector("[data-p-debt]")?.addEventListener("click",newDebt);document.querySelectorAll("[data-p-month]").forEach(b=>b.onclick=()=>chooseMonth(Number(b.dataset.pMonth)));document.querySelector("[data-p-sync]")?.addEventListener("click",sync);};
})();
