(() => {
  const KEY = "patrimonio-pwa-data-v1", FILE = "patrimonio-pwa.json";
  const euro = new Intl.NumberFormat("pt-PT", { style:"currency", currency:"EUR" });
  let selectedMonth = "";
  let portfolio;
  try { portfolio = JSON.parse(localStorage.getItem(KEY)); } catch { portfolio = null; }
  const empty = () => ({ schemaVersion:1, updatedAt:new Date().toISOString(), registos:[], dividas:[], catalog:{products:[],notesByProduct:{}}, drive:{fileName:FILE,fileId:"",syncStatus:"local"} });
  const p = () => portfolio || empty();
  const month = (date) => date.slice(0,7);
  const key = (institution, product) => `${institution}|${product}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
  const save = () => { p().updatedAt=new Date().toISOString(); localStorage.setItem(KEY,JSON.stringify(p())); };
  const months = () => [...new Set(p().registos.map(r=>month(r.data)).concat(p().dividas.map(d=>month(d.data))))].sort().reverse();
  const current = () => selectedMonth || months()[0] || new Date().toISOString().slice(0,7);
  const label = (m) => new Intl.DateTimeFormat("pt-PT",{month:"long",year:"numeric"}).format(new Date(`${m}-02T12:00:00`));
  const nav = () => `<nav class="bottom-nav"><button class="nav-button" data-page="transfers">Transferências</button><button class="nav-button active patrimony-nav" data-page="patrimony">Património</button><button class="nav-button" data-page="rules">Rubricas</button><button class="nav-button" data-page="settings">Dados</button></nav>`;
  function page(){
    if(!portfolio) return `<header class="page-header patrimony-head"><div><p class="eyebrow">Património</p><h1>Começar histórico</h1></div></header><div class="empty-card"><p>Importe o seu ficheiro histórico <strong>bens.json</strong> ou <strong>patrimonio-pwa.json</strong>. Os dados ficam locais até os sincronizar com o Drive.</p><br><button class="button patrimony-button" data-p-import>Importar histórico</button><input id="patrimony-import" type="file" accept="application/json" hidden></div>${nav()}`;
    const m=current(), rows=p().registos.filter(r=>month(r.data)===m), debts=p().dividas.filter(d=>month(d.data)===m), assets=rows.reduce((sum,r)=>sum+Number(r.valor||0),0), debt=debts.reduce((sum,d)=>sum+Number(d.valor||0),0);
    return `<header class="page-header patrimony-head"><div><p class="eyebrow">Património</p><h1>${label(m)}</h1></div><button class="button patrimony-button" data-p-new>+ Registo</button></header><div class="month-picker patrimony-picker"><button class="icon-button" data-p-month="-1">‹</button><strong>${label(m)}</strong><button class="icon-button" data-p-month="1">›</button></div><section class="summary patrimony-summary"><div class="summary-heading"><div><small>Património líquido</small><div class="summary-value">${euro.format(assets-debt)}</div><small>Ativos menos dívidas</small></div><button class="summary-edit" data-p-note>+ Nota</button></div><div class="summary-grid"><div><small>Ativos</small><div class="summary-value">${euro.format(assets)}</div></div><div><small>Dívidas</small><div class="summary-value">${euro.format(debt)}</div></div></div></section><div class="section-title"><h2>Ativos</h2><span class="muted">${rows.length}</span></div>${rows.length?rows.map(r=>`<div class="list-row patrimony-row"><div><strong>${r.instituicao} · ${r.produto}</strong><span>${r.data}</span></div><strong>${euro.format(r.valor)}</strong></div>`).join(""):`<div class="empty-card">Sem registos neste mês.</div>`}<div class="section-title"><h2>Dívidas</h2><span class="muted">${debts.length}</span></div>${debts.length?debts.map(d=>`<div class="list-row patrimony-row"><div><strong>${d.tipo||"Dívida"}</strong><span>${d.data}</span></div><strong>${euro.format(d.valor)}</strong></div>`).join(""):`<div class="empty-card">Sem dívidas neste mês.</div>`}<div class="section-title"><h2>Sincronização</h2></div><div class="list-row"><div><strong>${p().drive.fileId?"Drive associado":"Cópia local"}</strong><span>${p().drive.fileId?FILE:"Importe e sincronize para criar o ficheiro"}</span></div><div class="row-actions"><button class="small-button" data-p-connect>Ligar</button><button class="small-button" data-p-sync>Sincronizar</button></div></div>${nav()}`;
  }
  function chooseMonth(offset){const all=months().sort();const i=all.indexOf(current());selectedMonth=all[Math.max(0,Math.min(all.length-1,i+offset))]||current();render();}
  function render(){ document.querySelector("#app").innerHTML=page(); window.bind(); }
  function normalize(input){const raw=input.registos?input:empty();const out={...empty(),...raw,catalog:{products:raw.catalog?.products||[],notesByProduct:raw.catalog?.notesByProduct||{}},drive:{...empty().drive,...raw.drive,fileName:FILE}};for(const r of out.registos){if(!out.catalog.products.some(x=>x.id===key(r.instituicao,r.produto)))out.catalog.products.push({id:key(r.instituicao,r.produto),institution:r.instituicao,product:r.produto});}return out;}
  function importFile(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{portfolio=normalize(JSON.parse(reader.result));save();selectedMonth="";render();toast("Histórico importado neste dispositivo.");}catch{toast("O ficheiro não contém um histórico válido.");}};reader.readAsText(file);}
  function newRecord(){const date=`${current()}-01`, opts=p().catalog.products.map(x=>`<option value="${x.institution} | ${x.product}"></option>`).join("");const dlg=document.createElement("dialog");dlg.innerHTML=`<form class="modal" method="dialog" id="p-form"><div class="modal-head"><h2>Novo registo</h2><button class="icon-button" value="cancel">×</button></div><div class="form-grid"><label>Instituição<input required name="institution" list="p-catalog"></label><label>Produto<input required name="product"></label><label>Valor (€)<input required min="0" step="0.01" type="number" name="value"></label><label>Data<input required type="date" name="date" value="${date}"></label><label class="full">Observação<input name="note" maxlength="240"></label></div><datalist id="p-catalog">${opts}</datalist><div class="modal-actions"><button class="button secondary" value="cancel">Cancelar</button><button class="button patrimony-button" value="default">Guardar</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener("close",()=>dlg.remove());dlg.querySelector("#p-form").addEventListener("submit",()=>{const f=new FormData(dlg.querySelector("#p-form")),institution=f.get("institution").trim(),product=f.get("product").trim(),id=key(institution,product);p().registos.push({data:f.get("date"),instituicao:institution,produto:product,valor:Number(f.get("value"))});if(!p().catalog.products.some(x=>x.id===id))p().catalog.products.push({id,institution,product});if(f.get("note").trim())(p().catalog.notesByProduct[id]||={})[month(f.get("date"))]=f.get("note").trim();save();selectedMonth=month(f.get("date"));render();toast("Registo guardado.");});}
  async function token(){return window.googleTokenForPortfolio();}
  async function find(access){const q=encodeURIComponent(`name = '${FILE}' and trashed = false`),r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&orderBy=modifiedTime desc&pageSize=1&fields=files(id)`,{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw Error("Não foi possível procurar o ficheiro no Drive.");return (await r.json()).files?.[0];}
  async function connect(){try{const access=await token(),file=await find(access);if(!file){toast("Ainda não existe patrimonio-pwa.json no Drive. Importe e sincronize primeiro.");return;}const r=await fetch(`https://www.googleapis.com/drive/v3/files/${file.id}?alt=media`,{headers:{Authorization:`Bearer ${access}`}});if(!r.ok)throw Error("Não foi possível carregar o património.");portfolio=normalize(await r.json());p().drive.fileId=file.id;save();selectedMonth="";render();toast("Património carregado do Drive.");}catch(e){toast(e.message||"Não foi possível ligar ao Drive.");}}
  async function sync(){if(!portfolio){toast("Importe primeiro o histórico.");return;}try{const access=await token();let id=p().drive.fileId;if(!id){const found=await find(access);if(found){toast("Já existe uma cópia no Drive. Use Ligar para a carregar.");return;}const created=await fetch("https://www.googleapis.com/drive/v3/files",{method:"POST",headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json"},body:JSON.stringify({name:FILE,mimeType:"application/json"})});if(!created.ok)throw Error("O Drive recusou a criação do ficheiro.");id=(await created.json()).id;p().drive.fileId=id;}const body=JSON.stringify(p(),null,2),headers={Authorization:`Bearer ${access}`,"Content-Type":"application/json"};const r=await fetch(`https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media`,{method:"PATCH",headers,body});if(!r.ok)throw Error("O Drive recusou a gravação.");save();render();toast("Património sincronizado.");}catch(e){toast(e.message||"Não foi possível sincronizar.");}}
  window.patrimonyPage=page;window.bindPatrimony=()=>{document.querySelector("[data-p-import]")?.addEventListener("click",()=>document.querySelector("#patrimony-import").click());document.querySelector("#patrimony-import")?.addEventListener("change",importFile);document.querySelector("[data-p-new]")?.addEventListener("click",newRecord);document.querySelectorAll("[data-p-month]").forEach(b=>b.onclick=()=>chooseMonth(Number(b.dataset.pMonth)));document.querySelector("[data-p-connect]")?.addEventListener("click",connect);document.querySelector("[data-p-sync]")?.addEventListener("click",sync);};
})();
